### ISSUE TITLE
Duplicate records in the MySQL database

### ISSUE THREAD

**Issue by nleo575** [tetujin/aware-client-ios-v2#8] opened 2019-10-09 18:57 UTC
There are records in the database that appear to have been duplicated. This didn't happen every time or with enough frequency to notice at first. This issue was noticed on the battery table but it may be present on other sensors. 

This appears to be a sync problem more than anything. 

Overall severity: Minor problem - 3 out of 5 where 5 is worse.
This was more of a nuisance than anything. Data should only be pushed to the database once, not multiple times. 

The app should be recording the last record number that it synced with the database to prevent duplication since the tables themselves don't have a unique primary key that would prevent this type of duplication.

**Comment by tetujin** [comment] 2020-03-05 03:56
HI @nleo575 

Thank you for your report. The issue is a library side-issue (AWAREFramework-iOS). 
[AWAREFramework-iOS](https://github.com/tetujin/AWAREFramework-iOS)

The issue is fixed on the latest version of the library. The library version is v1.10.2.

Also, the version is included in the latest version of the client on AppStore.

I would like to close this Issue. Please reopen this issue if you face the same issue.

**Closed by tetujin** 2020-03-05 03:56 UTC
