### ISSUE TITLE
App overrides dashboard settings - Activity sensor

### ISSUE THREAD

**Issue by nleo575** [tetujin/aware-client-ios-v2#7] opened 2019-10-09 18:53 UTC
App sometimes oversamples activity. We had our frequency setting to 60 seconds, but sometimes we would get three observations in a one minute period instead of only one. 

This issue was repeatable and present on 100% (8 of 8) iPhones during our test.

Overall severity: Minor problem - 3 out of 5 where 5 is worse.
This was more of a nuisance than anything since we were just getting more data than requested.

**Comment by tetujin** [comment] 2020-03-05 01:24
Hi @nleo575 , Thank you for the report. I fixed the over-sample and un-periodical sampling issue. Please check the actions.

The reason for the issue is that CoreMotion (original data source) provides only activity change events. I added a function to supplement the dropped data.

**Comment by tetujin** [comment] 2020-03-14 02:52
This issue is fixed on the latest version of AWARE library ([AWAREFramework-iOS](https://github.com/tetujin/AWAREFramework-iOS)) version 1.10.4.

**Closed by tetujin** 2020-03-14 02:52 UTC
