### ISSUE TITLE
Activating Contacts Sensor Crashes app

### ISSUE THREAD

**Issue by nleo575** [tetujin/aware-client-ios-v2#9] opened 2019-10-10 15:01 UTC
The application crashed when I tried to activate the contacts sensor. This happened before I clicked the allow prompt for AWARE to access my contacts. I was able to turn on the sensor after force closing the app, going to iOS's Settings -> AWARE and turning on the slider for Contacts, and finally restarting AWARE. 

Overall severity: Major problem - 4 out of 5 where 5 is worse.

**Comment by tetujin** [comment] 2020-03-05 03:50
Hi @nleo575 

I could not reproduce the same error on my iPhone 11 (iOS 13.3). I think the issue is fixed in the previous update. 

I would like to close this issue. Please reopen this Issue if you face the same issue.

**Closed by tetujin** 2020-03-05 03:50 UTC
